# Project information
site_name: Gluu Solo 1.0 Docs
site_description: Documentation for Gluu Solo

# Copyright
copyright: Copyright &copy; 2021, Gluu, Inc.

# Repository
docs_dir: source
repo_name: GluuFederation/docs-solo-prod
repo_url: https://github.com/GluuFederation/docs-solo-prod/
edit_uri: edit/1.0/docs/source

# Configuration
theme:
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '1.0'

# Tracking
google_analytics:
  - 'UA-31008645-7'
  - 'auto'

# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '1.0': 'https://gluu.org/docs/ce/1.0/'
#    - 'eol': 'https://gluu.org/docs/eol/'
- ' ': 'https://gluu.org/docs'
- ' ': 'https://gluu.org/docs'
- Home: 'index.md'
